services:

  app:
    build: .
    volumes:
      - ./:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest 
    # --- takes the latest picture of 
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: geheim    
      # --- passwort ist immer geheim
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always          
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: geheim
    volumes:                 
      - pg-data:/var/lib/postgresql/data

volumes:
  pgadmin-data:
  pg-data: